name: Deploy ALB Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Terraform Init
        run: terraform init
        working-directory: alb

      - name: Terraform Plan
        run: terraform plan
        working-directory: alb

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: alb
