name: Deploy ALB Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # Step 2: Configure AWS Credentials (Use AWS Access Key and Secret Access Key)
      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # Replace with the region of your choice
        run: |
          echo "AWS credentials configured"

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: alb

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: alb

      # Step 6: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: alb
