name: Deploy ALB Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # Step 2: Manually configure AWS CLI with credentials
      - name: Configure AWS CLI (Manual setup)
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1  # Change to your AWS region if needed

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: alb

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: alb

      - name: Terraform apply
        run: terraform apply -auto-approve
        working-directory: alb


      

      
