name: Terraform CI/CD Workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.4.0"  # Use the latest version of Terraform

    - name: Initialize Terraform (without backend)
      run: terraform init -backend=false  # Initial run to create resources (S3 & DynamoDB)

    - name: Apply Terraform (to create the S3 bucket and DynamoDB)
      run: terraform apply -auto-approve

    - name: Update Backend Configuration with S3 Bucket
      run: |
        BUCKET_NAME=$(terraform output -raw s3_bucket_name)
        sed -i "s|bucket = .*|bucket = \"$BUCKET_NAME\"|" backend.tf
        terraform init -reconfigure  # Reinitialize with the correct backend

    - name: Plan Terraform
      run: terraform plan

    - name: Apply Terraform
      run: terraform apply -auto-approve

    - name: Generate Terraform Documentation (optional)
      run: terraform-docs markdown . > README.md
